### PR TITLE
Fixed logging not working, when not writing in batches

### LINKED ISSUE #46: Dot in field name error
Hi. I use **NLog.Targets.ElasticSearch** and I found a bug:
I log an **System.AggregateException**, who contains field **InnerExceptions** (enumerable type). **InnerExceptions** contains an **System.Data.SqlClient.SqlException** with filled **Data** field, who has Keys with dot in theirs names (ex. "**HelpLink.BaseHelpUrl**").
Extension method **ExpandoObjectExtensions.ReplaceDotInKeys** ignore enumerable types and ElasticClient send JSON with dots in field names.
I propose the following fix:
```csharp
public static ExpandoObject ReplaceDotInKeys(this ExpandoObject obj)
{
    var clone = new ExpandoObject();
    foreach (var item in obj)
    {
        if (item.Value == null)
            continue;                

        if (item.Value.GetType() == typeof(ExpandoObject))
            ((IDictionary<string, object>)clone)[item.Key.Replace('.', '_')]
                = (item.Value as ExpandoObject).ReplaceDotInKeys();
        // New code block >>>
        else if (item.Value is IEnumerable<object>)
        {
            var enumerableClone = new List<ExpandoObject>();
            foreach (var el in (item.Value as IEnumerable<object>))
            {
                if (el is ExpandoObject)
                    enumerableClone.Add(ReplaceDotInKeys(el as ExpandoObject));
            }
            ((IDictionary<string, object>)clone)[item.Key.Replace('.', '_')] = enumerableClone;
        }
        // <<< New code block
        else if (item.Key.Contains('.'))
            ((IDictionary<string, object>)clone)[item.Key.Replace('.', '_')] = item.Value;
        else
            ((IDictionary<string, object>)clone)[item.Key] = item.Value;
    }
    return clone;
}
```

### LINKED ISSUE #53: Logs not written to ElasticSearch
I am trying to use the newest beta from nuget, I am using the beta, because we want our log-library to be in .net Core. However nothing is written to ElasticSearch.
I think the problem is that ElasticSearchTarget does not overrice the method Write(LogEventInfo logEvent) from the NLog.Targets.Target class. That causes NLog to just call its own empty class:

        protected virtual void Write(LogEventInfo logEvent)
        {
            // Override to perform the actual write-operation
        }

An implementation in the ElasticSearchTarget like this will write the events:

        protected override void Write(LogEventInfo logEvent)
        {
            Write(new List<AsyncLogEventInfo> {new AsyncLogEventInfo(logEvent, exception => {})});
        }

At least that is my understanding.

### LINKED ISSUE #54: Minimize allocations for IncludeAllProperties
https://github.com/ReactiveMarkets/NLog.Targets.ElasticSearch/blob/e4558f1f99e104f6f7f9c6b4d730d0a2e898c2af/src/NLog.Targets.ElasticSearch/ElasticSearchTarget.cs#L192

Minimize allocations by doing it like this:

```
if (IncludeAllProperties)
{
   if (logEvent.Properties.Count > 0)
   {
       foreach (var p in logEvent.Properties)
       {
            var propertyKey = p.Key.ToString();
            if (_excludedProperties.Contains(propertyKey))
                 continue;
            if (document.ContainsKey(propertyKey))
                 continue;

            document[propertyKey] = p.Value;
       }
   }
}
```

### PR DESCRIPTION
**Pull request by snakefoot**
(and reduced allocations)

Resolves #54 and resolves #53

### CODE REVIEW

**Comment by snakefoot** [comment]
@markmcdowell Any chance this can be approved and merged?

**Comment by snakefoot** [comment]
@markmcdowell Polite ping...

**Comment by 304NotModified** [comment]
LGTM

**Comment by 304NotModified** [comment]
NLog 4.5 RTM is now also live, so https://github.com/ReactiveMarkets/NLog.Targets.ElasticSearch/pull/61

**Pull request merged**
