### PR TITLE
Support getting the connection string from an environment variable.

### PR DESCRIPTION
**Pull request by ejsmith**

### CODE REVIEW

**Comment by ejsmith** [comment]
I am using environment variables in azure to do my configuration, so I need this target to pickup my connection string from there.

**Comment by ejsmith** [comment]
Any chance of accepting this pull request?

**Comment by ejsmith** [comment]
Awesome. Thank you.

**Comment by ejsmith** [comment]
Will this automatically go out to nuget?

**Comment by markmcdowell** [comment]
No not yet, it's building on appveyor but i haven't setup the auto deploy.

**Comment by markmcdowell** [comment]
i've kicked off the deploy

**Comment by ejsmith** [comment]
Awesome!  Thanks.

**Pull request merged**
