### PR TITLE
Support using a connectionstring name for config.

### PR DESCRIPTION
**Pull request by ejsmith**
Convert the Exception object to a string so that it doesn't break when being serialized by SimpleJson.
Only add fields if they render non empty values.
Change default index name to match the official logstash format.
Add some error handling.

### CODE REVIEW

**Comment by niemyjski** [comment]
+1

**Comment by ejsmith** [comment]
Would love to get rid of my custom build. Do you happen to automatically deploy new versions to NuGet?

**Comment by markmcdowell** [comment]
It's not automated it the moment, just manually through the pack and publish bat files in tools. I've published 0.9.4 including this pr into NuGet.

**Comment by ejsmith** [comment]
Awesome! Thank you.

**Pull request merged**
