### PR TITLE
Pipeline parameter for Elasticsearch ingestion 

### PR DESCRIPTION
**Pull request by DistSynth**
Pipeline parameter for preprocessing log messages by [Ingest node](https://www.elastic.co/guide/en/elasticsearch/reference/master/ingest.html) and [pipeline](https://www.elastic.co/guide/en/elasticsearch/reference/master/pipeline.html)

### CODE REVIEW

**Comment by markmcdowell** [comment]
Thanks for the PR!

**Comment by aheubusch** [comment]
This PR doesnt work when targeting ElasticSearch server version < 5.X.
`{ServerError: 400 Type: illegal_argument_exception Reason: "Action/metadata line [1] contains an unknown parameter [pipeline]"}`

**Comment by markmcdowell** [comment]
Damn, I did think to check that at the time I was approving it. Will revert, waiting on elasticsearch client for v5 support.

Thanks, Mark




On Fri, Feb 10, 2017 at 8:31 AM +0000, "Alexander Heubusch" <notifications@github.com> wrote:












This PR doesnt work when targeting ElasticSearch server version < 5.X.

{ServerError: 400 Type: illegal_argument_exception Reason: "Action/metadata line [1] contains an unknown parameter [pipeline]"}

**Comment by kpa6uk** [comment]
Hey, @markmcdowell, it is affecting our setup too.
We have ES 2.3 on our logs cluster, soooo when will you revert this?

To whom it may concern: latest version without this change is https://www.nuget.org/packages/NLog.Targets.ElasticSearch/2.1.6

**Comment by markmcdowell** [comment]
My laptop is currently with Apple being fixed... so it'll be either next week or if someone raises a PR to fix/revert. :/

Thanks, Mark




On Thu, Feb 16, 2017 at 12:22 PM +0000, "Карбовничий Вячеслав" <notifications@github.com> wrote:












Hey, @markmcdowell, it is affecting our setup too.

We have ES 2.3 on our logs cluster, soooo when will you revert this?


To whom it may concern: latest version without this change is https://www.nuget.org/packages/NLog.Targets.ElasticSearch/2.1.6

**Pull request merged**
